EWM #1:  ревью основного задания
Indiannka/java-explore-with-me pull request #2
Opened 2022-11-12 15:01 UTC by Indiannka

EWM-service: #1 Разработан основной сервис, сервис статистики и клиент статистики.

2022-11-29 20:28 UTC, krylov-sergey-sergeevich requested changes
Привет, слишком хорошая работа и я сейчас как-то не приходит на ум что можно сделать сильно лучше

Поэтому давай поправим мелочи которые отметил и 

1) Почитай о свагер это сделает проект еще лучше
2) Подход с исключениями хорош, но можно лучше. Исключения если присмотреться похожи по структуре, не хочется ли создать структуру исключений или побольше кастомных исключений и не писать каждый раз весь текст причины исключения, а чисто название например NotFoundCategoryException extend NotFoundException это не обязательно, но как на подумать.

Буду ждать с доработкой =)

2022-11-29 20:28 UTC, krylov-sergey-sergeevich commented on ewm-service/pom.xml
> +        <dependency>
Впервые вижу что студент применяет, лайк

2022-11-29 20:28 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/configs/Constants.java
> +public class Constants {
Лайк за такой класс

2022-11-29 20:28 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/configs/EntityMapper.java
> +public class EntityMapper {
Так это маппер или сервис получения евента?

2022-11-29 20:28 UTC, krylov-sergey-sergeevich commented on ewm-service/src/main/java/ru/practicum/ewm/event/EventServiceImpl.java
> +        int page = from / size;
Мне кажется такое лучше вынести в утилитный класс ибо может повторяться достаточно часто

2022-11-29 20:28 UTC, krylov-sergey-sergeevich commented on stats-server/pom.xml
> +            <version>1.5.3.Final</version>
Версии лучше выносить в блок с properties в pom.xml

2022-11-30 18:55 UTC, Indiannka commented on ewm-service/src/main/java/ru/practicum/ewm/configs/EntityMapper.java
> +public class EntityMapper {
Это вспомогательный класс для compilationMapper. Дело в том, что маппер не мог определить какой метод выбрать в сервисе ивента  для возврата сущности по id (так как там несколько методов, которые возвращают Event, а в аргументах только id) и при конвертации ничего не заполнял кроме id события. Поэтому я вынесла этот метод отдельно и указала на него в маппере...

2022-11-30 18:56 UTC, Indiannka commented on stats-server/pom.xml
> +            <version>1.5.3.Final</version>
Вроде все перенесла теперь.

2022-11-30 19:05 UTC, Indiannka commented
Привет! Спасибо большое! Сделала правки :)

1. По поводу swagger немного подвисла, идея в том чтобы интегрировать его с git, если я правильно поняла? Если это делается через Pages, то нужно еще поразбираться :)
2. Повторяющиеся эксепшены отрефакторила в Event, но в Request оставила, не знаю стоит ли делать отдельный Ecxeption на единичные ситуации.

2022-11-30 19:05 UTC, Indiannka commented on ewm-service/src/main/java/ru/practicum/ewm/configs/Constants.java
> +public class Constants {
+

2022-11-30 19:05 UTC, Indiannka commented on ewm-service/pom.xml
> +        <dependency>
+

2022-12-01 19:35 UTC, krylov-sergey-sergeevich approved these changes
Привет

Сваггер - https://habr.com/ru/post/541592/ (статья устаревшая, но как ознакомление сойдет)

Свагер это многогранная штука, но базово это добавление аннотаций к контроллеру чтобы в последующем сгенерировать документацию в которой сразу можно будет видеть API сервиса с описанием. C git/github ничего интегрировать не нужно, это просто как часть кода будет =)

В общем работа отличная - зачет! Видно что вы овладели языком Java и сопуствующими технологиями.

2022-12-01 19:35 UTC, krylov-sergey-sergeevich commented on README.md
> +# Архитектура проекта
В readme можно будет после добавить блок "Используемые технологии" чтобы потенциально если кто-то будет смотреть ваш гитхаб и прикидывать что вы умете у вас по проекту было понятно что вы уже применяли

2022-12-04 19:10 UTC, Indiannka commented on stats-server/pom.xml
> +            <version>1.5.3.Final</version>
Сергей, большое спасибо! Спасибо за сваггер, поэксперементирую, пригодится для работы.

2022-12-06 18:31 UTC, merged